#!/usr/bin/env bash
# Optional curriculum runner: Stages 0→3 with reduced epoch budgets.
# Each stage calls mbpo run_local WITHOUT --restore (independent trials).
# For gate-ready Stage 0/1 runs, use docs/TRAINING_PROTOCOL.md §0 + full configs.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$ROOT/examples/config/pv_tracking"
RAY_ROOT="${RAY_ROOT:-$HOME/ray_mbpo/PVTracking/pv_tracking}"
ARTIFACT_DIR="$ROOT/sequential_stage_artifacts"
EVAL_ROOT="$ROOT/evaluation"

CONDA_SH="${CONDA_SH:-$HOME/miniconda3/etc/profile.d/conda.sh}"
CONDA_ENV_NAME="${CONDA_ENV_NAME:-mbpo}"

CPUS="${CPUS:-4}"
TRIAL_CPUS="${TRIAL_CPUS:-2}"
GPUS="${GPUS:-0}"
TRIAL_GPUS="${TRIAL_GPUS:-0}"
EVAL_ROLLOUTS="${EVAL_ROLLOUTS:-8}"
MAX_PATH_LENGTH="${MAX_PATH_LENGTH:-39}"
STOP_ON_GATE_FAIL="${STOP_ON_GATE_FAIL:-0}"
STAGE3_VALIDATION_DATES="2020-02-15,2020-05-15,2020-08-15,2020-11-15"

mkdir -p "$ARTIFACT_DIR"
mkdir -p "$EVAL_ROOT"

if [[ ! -f "$CONDA_SH" ]]; then
  echo "Missing conda init script: $CONDA_SH" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$CONDA_SH"
conda activate "$CONDA_ENV_NAME"
cd "$ROOT"

write_generated_configs() {
  cat > "$CONFIG_DIR/stage0_curriculum_100.py" <<'PY'
"""Generated by run_sequential_stages.sh.

Stage 0 wrapper: keep the verified single-day physical setup and only reduce the
epoch budget to 100 for curriculum warm-up.
"""

from pathlib import Path
import runpy

_base = runpy.run_path(str(Path(__file__).with_name('stage0_single_day.py')))

CONFIG_VERSION = 'pv_tracking_stage0_single_day_curriculum100_2026-05-25'
TRAINING_STAGE = 'stage0'

params = dict(_base['params'])
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base['params']['kwargs'])
params['kwargs'].update({
    'n_epochs': 100,
})
PY

  cat > "$CONFIG_DIR/stage1_curriculum_200.py" <<'PY'
"""Generated by run_sequential_stages.sh.

Stage 1 wrapper: keep the verified summer clearsky physical setup and only
reduce the epoch budget to 200 for curriculum warm-up.
"""

from pathlib import Path
import runpy

_base = runpy.run_path(str(Path(__file__).with_name('0.py')))

CONFIG_VERSION = 'pv_tracking_stage1_clearsky_curriculum200_2026-05-25'
TRAINING_STAGE = 'stage1'

params = dict(_base['params'])
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base['params']['kwargs'])
params['kwargs'].update({
    'n_epochs': 200,
})
PY

  cat > "$CONFIG_DIR/stage2_curriculum_300.py" <<'PY'
"""Generated by run_sequential_stages.sh.

Stage 2 wrapper: keep the verified summer historical-weather physical setup and only
reduce the epoch budget to 300 for curriculum warm-up.
"""

from pathlib import Path
import runpy

_base = runpy.run_path(str(Path(__file__).with_name('stage2_random_weather.py')))

CONFIG_VERSION = 'pv_tracking_stage2_random_weather_curriculum300_2026-05-25'
TRAINING_STAGE = 'stage2'

params = dict(_base['params'])
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base['params']['kwargs'])
params['kwargs'].update({
    'n_epochs': 300,
})
PY

  cat > "$CONFIG_DIR/stage3_curriculum_500_clean_split.py" <<'PY'
"""Generated by run_sequential_stages.sh.

Stage 3 wrapper: use the full-year historical-weather clean-split Stage 3 config and keep the
500-epoch budget for curriculum training. Validation dates are used for
in-training checkpoint selection; untouched final-test dates are reserved for
run_stage3_posttrain.sh.
"""

import importlib

_base = importlib.import_module('examples.config.pv_tracking.stage3_fullyear_random_clean_split')

CONFIG_VERSION = 'pv_tracking_stage3_fullyear_random_clean_split_curriculum500_2026-05-26'
TRAINING_STAGE = 'stage3'

params = dict(_base.params)
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base.params['kwargs'])
params['kwargs'].update({
    'n_epochs': 500,
})
params['environment_kwargs'] = dict(_base.params['environment_kwargs'])
params['evaluation_environment_kwargs'] = dict(_base.params['evaluation_environment_kwargs'])
PY
}

validate_balanced_eval_rollouts() {
  local fixed_eval_dates="$1"
  IFS=',' read -r -a dates <<< "$fixed_eval_dates"
  local date_count="${#dates[@]}"
  if (( date_count > 1 )) && (( EVAL_ROLLOUTS % date_count != 0 )); then
    echo "EVAL_ROLLOUTS=$EVAL_ROLLOUTS must be a multiple of $date_count for balanced fixed-date evaluation coverage." >&2
    exit 1
  fi
}

snapshot_trials() {
  if [[ -d "$RAY_ROOT" ]]; then
    ls -1d "$RAY_ROOT"/seed:* 2>/dev/null | sed 's:/$::' || true
  fi
}

wait_for_new_trial() {
  local -a before_trials=("$@")
  local -A seen=()
  local candidate

  for candidate in "${before_trials[@]:-}"; do
    seen["$candidate"]=1
  done

  for _ in $(seq 1 300); do
    mapfile -t current_trials < <(snapshot_trials)
    for candidate in "${current_trials[@]:-}"; do
      if [[ -z "${seen[$candidate]:-}" ]]; then
        echo "$candidate"
        return 0
      fi
    done
    sleep 2
  done

  echo "Timed out waiting for a new Ray trial under $RAY_ROOT" >&2
  return 1
}

prepare_eval_dir() {
  local eval_dir="$1"
  if [[ -d "$eval_dir" ]]; then
    mv "$eval_dir" "${eval_dir}_backup_$(date +%Y%m%d_%H%M%S)"
  fi
}

best_checkpoint_for_trial() {
  local trial_dir="$1"

  if [[ -d "$trial_dir/best_eval_checkpoint" ]]; then
    echo "$trial_dir/best_eval_checkpoint"
    return 0
  fi

  local latest=""
  latest=$(ls -1d "$trial_dir"/checkpoint_* 2>/dev/null | sort -V | tail -1 || true)
  if [[ -n "$latest" ]]; then
    echo "$latest"
    return 0
  fi

  echo "No checkpoint directory found under $trial_dir" >&2
  return 1
}

verify_trial_contract() {
  local trial_dir="$1"
  local expected_stage="$2"
  local expected_weather="$3"
  local expected_start="$4"
  local expected_end="$5"
  local expected_randomize="$6"

  python - "$trial_dir" "$expected_stage" "$expected_weather" "$expected_start" "$expected_end" "$expected_randomize" <<'PY'
import json
import sys

trial_dir, expected_stage, expected_weather, expected_start, expected_end, expected_randomize = sys.argv[1:]
variant = json.load(open(f"{trial_dir}/params.json"))
config_version = variant.get('config_version', '')
env = variant['environment_params']['training']['kwargs']

assert variant.get('restore') in (None, ''), (
    f"trial must be fresh (no --restore): {variant.get('restore')!r}")
assert variant.get('run_params', {}).get('checkpoint_replay_pool') is not True

assert expected_stage in config_version.lower(), (
    f"wrong config_version for {trial_dir}: {config_version!r}")
assert env.get('observation_mode') == 'physical', env.get('observation_mode')
assert str(env.get('weather_source')) == expected_weather, env.get('weather_source')
assert str(env.get('start_date')) == expected_start, env.get('start_date')
assert str(env.get('end_date')) == expected_end, env.get('end_date')

expected_randomize_bool = expected_randomize.lower() == 'true'
assert bool(env.get('randomize_day')) is expected_randomize_bool, env.get('randomize_day')

print('config_version:', config_version)
print('train weather_source:', env.get('weather_source'))
print('train randomize_day:', env.get('randomize_day'))
print('train date range:', env.get('start_date'), '->', env.get('end_date'))
print('observation_mode:', env.get('observation_mode'))
PY
}

run_stage() {
  local stage_name="$1"
  local config_module="$2"
  local config_path="$3"
  local eval_dir="$4"
  local fixed_eval_dates="$5"
  local eval_weather="$6"
  local expected_stage="$7"
  local expected_start="$8"
  local expected_end="$9"
  local expected_randomize="${10}"

  echo
  echo "========== ${stage_name} =========="
  echo "Config module: $config_module"
  echo "Config path:   $config_path"
  echo "Training:      fresh trial (no --restore, no cross-stage weights)"

  validate_balanced_eval_rollouts "$fixed_eval_dates"
  python scripts/verify_training_config.py --config "$config_module"
  python scripts/validate_pv_rollouts.py --config-path "$config_path"

  mapfile -t before_trials < <(snapshot_trials)
  local log_file="$ARTIFACT_DIR/${stage_name}_train_$(date +%Y%m%d_%H%M%S).log"

  (
    mbpo run_local examples.development \
      --config="$config_module" \
      --gpus="$GPUS" \
      --trial-gpus="$TRIAL_GPUS" \
      --cpus="$CPUS" \
      --trial-cpus="$TRIAL_CPUS" \
      2>&1 | tee "$log_file"
  ) &
  local train_pid=$!

  local new_trial
  new_trial="$(wait_for_new_trial "${before_trials[@]:-}")"
  echo "$new_trial" > "$ARTIFACT_DIR/${stage_name}_trial_dir.txt"

  wait "$train_pid"

  verify_trial_contract \
    "$new_trial" \
    "$expected_stage" \
    "$eval_weather" \
    "$expected_start" \
    "$expected_end" \
    "$expected_randomize"

  local ckpt
  ckpt="$(best_checkpoint_for_trial "$new_trial")"
  echo "$ckpt" > "$ARTIFACT_DIR/${stage_name}_checkpoint_dir.txt"

  prepare_eval_dir "$eval_dir"
  python scripts/evaluate_agent.py "$ckpt" \
    --outdir "$eval_dir" \
    --num-rollouts "$EVAL_ROLLOUTS" \
    --max-path-length "$MAX_PATH_LENGTH" \
    --deterministic \
    --compare-baselines \
    --fixed-eval-dates "$fixed_eval_dates" \
    --eval-weather-source "$eval_weather" \
    --eval-protocol inherit

  set +e
  python scripts/diagnose_tracking.py \
    --eval-dir "$eval_dir" \
    --outdir "$eval_dir/diagnostics" \
    --progress-csv "$new_trial/progress.csv" \
    --trial-dir "$new_trial" \
    --gate
  local gate_status=$?
  set -e

  if [[ "$gate_status" -ne 0 ]]; then
    echo "$gate_status" > "$ARTIFACT_DIR/${stage_name}_gate_status.txt"
    echo "[${stage_name}] gate failed with status ${gate_status}; continuing curriculum training."
    if [[ "$STOP_ON_GATE_FAIL" == "1" ]]; then
      echo "[${stage_name}] STOP_ON_GATE_FAIL=1, aborting after failed gate." >&2
      return "$gate_status"
    fi
  else
    echo "0" > "$ARTIFACT_DIR/${stage_name}_gate_status.txt"
  fi
}

write_generated_configs

run_stage \
  "stage0" \
  "examples.config.pv_tracking.stage0_curriculum_100" \
  "$CONFIG_DIR/stage0_curriculum_100.py" \
  "$EVAL_ROOT/pv_stage0_single_day" \
  "2020-06-21" \
  "clearsky" \
  "stage0" \
  "2020-06-21" \
  "2020-06-21" \
  "false"

run_stage \
  "stage1" \
  "examples.config.pv_tracking.stage1_curriculum_200" \
  "$CONFIG_DIR/stage1_curriculum_200.py" \
  "$EVAL_ROOT/pv_stage1_clearsky_summer" \
  "2020-06-07,2020-06-21,2020-07-15,2020-08-01" \
  "clearsky" \
  "stage1" \
  "2020-06-01" \
  "2020-08-31" \
  "true"

run_stage \
  "stage2" \
  "examples.config.pv_tracking.stage2_curriculum_300" \
  "$CONFIG_DIR/stage2_curriculum_300.py" \
  "$EVAL_ROOT/pv_stage2_random_weather_summer" \
  "2020-06-07,2020-06-21,2020-07-15,2020-08-01" \
  "historical" \
  "stage2" \
  "2020-06-01" \
  "2020-08-31" \
  "true"

run_stage \
  "stage3" \
  "examples.config.pv_tracking.stage3_curriculum_500_clean_split" \
  "$CONFIG_DIR/stage3_curriculum_500_clean_split.py" \
  "$EVAL_ROOT/pv_stage3_validation_clean_split" \
  "$STAGE3_VALIDATION_DATES" \
  "historical" \
  "stage3" \
  "2020-01-01" \
  "2020-12-31" \
  "true"

echo
echo "All stages completed."
echo "Trial paths: $ARTIFACT_DIR/*_trial_dir.txt"
echo "See docs/TRAINING_PROTOCOL.md §0 for clean per-stage eval."
