"""Generated by run_sequential_stages.sh.

Stage 1 wrapper: keep the verified summer clearsky physical setup and only
reduce the epoch budget to 200 for curriculum warm-up.
"""

from pathlib import Path
import runpy

_base = runpy.run_path(str(Path(__file__).with_name('0.py')))

CONFIG_VERSION = 'pv_tracking_stage1_clearsky_curriculum200_2026-05-25'
TRAINING_STAGE = 'stage1'

params = dict(_base['params'])
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base['params']['kwargs'])
params['kwargs'].update({
    'n_epochs': 200,
    'real_ratio': 0.9,
})
