"""Generated by run_sequential_stages.sh.

Stage 0 wrapper: keep the verified single-day physical setup and only reduce the
epoch budget to 100 for curriculum warm-up.
"""

from pathlib import Path
import runpy

_base = runpy.run_path(str(Path(__file__).with_name('stage0_single_day.py')))

CONFIG_VERSION = 'pv_tracking_stage0_single_day_curriculum100_2026-05-25'
TRAINING_STAGE = 'stage0'

params = dict(_base['params'])
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base['params']['kwargs'])
params['kwargs'].update({
    'n_epochs': 100,
})
