"""Generated by run_sequential_stages.sh.

Stage 2 wrapper: keep the verified summer random-weather physical setup and only
reduce the epoch budget to 300 for curriculum warm-up.
"""

from pathlib import Path
import runpy

_base = runpy.run_path(str(Path(__file__).with_name('stage2_random_weather.py')))

CONFIG_VERSION = 'pv_tracking_stage2_random_weather_curriculum300_2026-05-25'
TRAINING_STAGE = 'stage2'

params = dict(_base['params'])
params['config_version'] = CONFIG_VERSION
params['kwargs'] = dict(_base['params']['kwargs'])
params['kwargs'].update({
    'n_epochs': 300,
    'real_ratio': 0.9,
})
